version: '3'
services:
  user-mysql:
    image: mysql:5.7
    network_mode: host
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: keepnotes
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_CI_URL: jdbc:mysql://localhost:3306/keepnotes
      MYSQL_HOST: localhost
  user-mongo:
    image: mongo:latest
    network_mode: host
    ports:
    - 27017:27017
    environment:
      MONGO_PORT: 27017
      MONGO_HOST: localhost
  authentication-service:
    image: elan/userauthenticationservice:v1
    build: 
       context: UserAuthentication-Service/
    restart: always
    network_mode: host
    depends_on:
    - user-mysql
    ports:
    - 8089:8089
  category-service:
    image: elan/categoryservice:v1
    build: 
       context: CategoryService/
    restart: always
    network_mode: host
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: categoryDb
      MONGO_PORT: 27017
      MONGO_HOST: localhost
    depends_on:
    - user-mongo
    ports:
    - 8083:8083
  note-service:
    image: elan/noteservice:v1
    build: 
       context: NoteService/
    restart: always
    network_mode: host
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: noteDb
      MONGO_PORT: 27017
      MONGO_HOST: localhost
    depends_on:
    - user-mongo
    ports:
    - 8082:8082
  reminder-service:
    image: elan/reminderservice:v1
    build: 
       context: ReminderService/
    restart: always
    network_mode: host
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: reminderDb
      MONGO_PORT: 27017
      MONGO_HOST: localhost
    depends_on:
    - user-mongo
    ports:
    - 8081:8081
  user-service:
    image: elan/userservice:v1
    build: 
       context: UserService/
    restart: always
    network_mode: host
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: userDb
      MONGO_PORT: 27017
      MONGO_HOST: localhost
    depends_on:
    - user-mongo
    ports:
    - 8080:8080